[package]
name = "mrh"
version = "0.3.1"
description = "Crawls filesystem and displays pending status of each git repo found"
repository = "https://github.com/tshepang/mrh"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["git"]
authors = ["Tshepang Lekhonkhobe <tshepang@gmail.com>"]

[dependencies]
git2 = "0.6"
structopt = "0.1"
structopt-derive = "0.1"
walkdir = "2"

[badges]
travis-ci = { repository = "tshepang/mrh" }
